apiVersion: v1
kind: Pod
metadata:
  labels:
    spark-app-selector: spark-406656d05d7f456f81fcde9530ae1d70
    spark-role: driver
  name: hello-eef5dd75bf27b19e-driver
  namespace: default
spec:
  serviceAccountName: job-trigger-sa
  containers:
    - name: spark-launcher
      image: __USERNAME__/spark:__SPARK_VERSION__
      imagePullPolicy: IfNotPresent
      env:
        - name: SPARK_USER
          value: __USERNAME__
        - name: HADOOP_USER_NAME
          value: __USERNAME__
        - name: HADOOP_PROXY_USER
          value: __USERNAME__
        - name: SPARK_LOCAL_DIRS
          value: /var/data/spark-851e63d2-1237-470e-846f-8efa9250f005
        - name: SPARK_CONF_DIR
          value: /opt/spark/conf
        - name: SPARK_APPLICATION_ID
          value: spark-406656d05d7f456f81fcde9530ae1d70
        - name: SPARK_DRIVER_BIND_ADDRESS
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
      command:
        - /opt/spark/bin/spark-submit
      args:
        - --master
        - k8s://https://kubernetes.default.svc.cluster.local:443
        - --deploy-mode
        - cluster
        - --name
        - hello
        - --class
        - demo.Count
        - --conf
        - spark.executor.instances=2
        - --conf
        - spark.kubernetes.container.image=__USERNAME__/spark-k8s-hello:__APP_VERSION__
        - --conf
        - spark.jars.ivy=/tmp/.ivy
        - --conf
        - spark.app.name=hello
        - --conf
        - spark.kubernetes.authenticate.driver.serviceAccountName=job-trigger-sa
        - --conf
        - spark.authenticate=false
        - local:///tmp/jars/spark-k8s-hello.jar
