apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-trigger-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["get", "watch", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-trigger-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: job-trigger-sa
    apiGroup: ""
    namespace: default
roleRef:
  kind: Role
  name: job-trigger-role
  apiGroup: rbac.authorization.k8s.io
